# Generated by Django 4.2 on 2024-02-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Customer First Name', max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(help_text='Customer Last Name', max_length=50, verbose_name='Last Name')),
                ('dob', models.DateField(help_text='Customer Date of Birth', verbose_name='Date of Birth')),
                ('phone_no', models.CharField(help_text='Customer phone number', max_length=13, verbose_name='Phone No.')),
            ],
            options={
                'ordering': ('first_name',),
            },
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'dob', 'phone_no'), name='unique_first_last_dob_phone'),
        ),
    ]
