# Generated by Django 4.2 on 2024-02-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='unique_first_last_dob_phone',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='test@gmail.com', help_text='Customer unique email id', max_length=254, verbose_name='Email ID'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('dob', 'phone_no', 'email'), name='unique_dob_phone_email'),
        ),
    ]
